app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fish.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(
  settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

app/fish/urls.py
from django.urls import path
from . import views

app_name = 'fish'

urlpatterns = [
    #　ホーム
    path('', views.index, name='index'),
    #　投稿作成
    path('fish/new/', views.article_create, name='article_create'),
    #　投稿詳細
    path('detail/<uuid:pk>/', views.article_detail, name='article_detail'),
    #　投稿編集
    path('edit/<uuid:pk>/', views.article_edit, name='article_edit'),
    #　投稿消去
    path('detail/<uuid:pk>/delete/',views.article_delete,name='article_delete'),
    #　コメント投稿
    path('detail/<uuid:pk>/comment/', views.comment_create, name='comment_create'),
    #　カテゴリー登録
    path('category_create', views.category_create, name='category_create'),
    #　場所登録
    path('place_create', views.place_create, name='place_create'),
    #　フリーワード検索
    path('search/', views.search, name='search'),
    #　魚種検索
    path('category_search/', views.category_search, name='category_search'),
    #　魚種検索結果
    path('category_result/', views.category_result, name='category_result'),
    #　場所検索
    path('place_search/', views.place_search, name='place_search'),
    #　場所検索結果
    path('place_result/', views.place_result, name='place_result'),
    #　みんなの釣果
    path('every_result', views.every_result, name='every_result'),
    #　Userページ
    path('users/<uuid:pk>/', views.mypage_detail, name='mypage_detail'),
    path('users/pading/<uuid:pk>/', views.mypage_pading, name='mypage_pading'),
    path('users/<uuid:pk>/edit', views.profile_edit, name='profile_edit'),
    #　コンタクトのurl
    path('contact/', views.contact_form, name='contact_form'),
    path('contact/result/', views.contact_result, name='contact_result'),
]

app/fish/forms.py
from django import forms
from django.conf import settings
from .models import Article, Category, Place, Profile, Comment
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['fish_category', 'fishing_comment', 'fish_img','length','weight','place']


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('target', 'created_at')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['user_name', 'icon', 'header', 'text']


class ContactForm(forms.Form):
    name = forms.CharField(
        label='',
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': "お名前",
        }),
    )
    email = forms.EmailField(
        label='',
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': "メールアドレス",
        }),
    )
    message = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': "お問い合わせ内容",
        }),
    )

    def send_email(self):
        subject = "お問い合わせ"
        message = self.cleaned_data['message']
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        from_email = '{name} <{email}>'.format(name=name, email=email)
        recipient_list = [settings.EMAIL_HOST_USER]  # 受信者リスト
        try:
            send_mail(subject, message, from_email, recipient_list)
        except BadHeaderError:
            return HttpResponse("無効なヘッダが検出されました。")

app/fish/forms/comment.py
from django import forms
from fish.models import Comment


# コメント
class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('target', 'created_at')

app/fish/forms/contact.py
from django import forms
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse


# 問い合わせ
class ContactForm(forms.Form):
    name = forms.CharField(
        label='',
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': "お名前",
        }),
    )
    email = forms.EmailField(
        label='',
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': "メールアドレス",
        }),
    )
    message = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': "お問い合わせ内容",
        }),
    )

    def send_email(self):
        subject = "お問い合わせ"
        message = self.cleaned_data['message']
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        from_email = '{name} <{email}>'.format(name=name, email=email)
        recipient_list = [settings.EMAIL_HOST_USER]  # 受信者リスト
        try:
            send_mail(subject, message, from_email, recipient_list)
        except BadHeaderError:
            return HttpResponse("無効なヘッダが検出されました。")

app/fish/forms/create.py
from django import forms
from django.conf import settings
from fish.models import Article, Category, Place, Profile, Comment

# 投稿
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['fish_category', 'fishing_comment', 'fish_img','length','weight','place']

        widgets = {
            'fishing_comment': forms.Textarea(attrs={'class': 'text',}),
        }

# プロフィール
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['user_name', 'icon', 'header', 'text']

# カテゴリー
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass',}),
        }

# 場所
class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = ['title']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass',}),
        }

app/fish/views/article.py
from django.shortcuts import redirect, get_object_or_404

from django.contrib.auth.mixins import LoginRequiredMixin 

from django.views.generic import CreateView, DeleteView, UpdateView, DetailView

from django.urls import reverse_lazy, reverse

from fish.models import Article, Profile, Comment

from fish.forms import ArticleForm, CommentCreateForm




# 作成
class ArticleCreateView(CreateView, LoginRequiredMixin):
    template_name = 'fish/article_new.html'
    success_url = reverse_lazy('fish:index')
    form_class = ArticleForm
    model = Article

    def form_valid(self, form):
        form = form.save(commit=False)
        form.user = self.request.user
        form.save()
        article = Article.objects.latest("created_at")
        article_id = str(article)
        url = '/detail/'
        return redirect(to=url + article_id)

article_create = ArticleCreateView.as_view()


# 詳細
class ArticlDetailview(DetailView):
    template_name = 'fish/article_detail.html'
    model = Article

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['article_list'] = Article.objects.filter(user=self.object.user).order_by('?')[:3]
        context['profile_list'] = Profile.objects.filter(user=self.object.user)
        context['comment'] = Comment.objects.filter(target=self.object.pk)
        return context

article_detail = ArticlDetailview.as_view()


#消去
class ArticleDeleteview(DeleteView, LoginRequiredMixin):
    model = Article
    success_url = reverse_lazy('fish:index')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != self.request.user:
            return redirect(self.success_url)
        return super().post(request, *args, **kwargs)

article_delete = ArticleDeleteview.as_view()


#変更
class ArticleUpdateView(UpdateView, LoginRequiredMixin):
    template_name = 'fish/article_edit.html'
    form_class = ArticleForm
    model = Article

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != self.request.user:
            return redirect(('fish:index'))
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('fish:article_detail', kwargs={'pk': self.object.pk})

article_edit = ArticleUpdateView.as_view()

app/fish/views/comment.py
from django.shortcuts import redirect, get_object_or_404


from django.views.generic import CreateView

from fish.models import Article, Comment

from fish.forms import CommentCreateForm


# コメント
class CommentCreate(CreateView):
    template_name = 'fish/comment_form.html'
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        article_pk = self.kwargs['pk']
        article = get_object_or_404(Article, pk=article_pk)
        comment = form.save(commit=False)
        comment.target = article
        comment.save()
        return redirect('fish:article_detail', pk=article_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['article'] = get_object_or_404(Article, pk=self.kwargs['pk'])
        return context

comment_create = CommentCreate.as_view()

app/fish/views/contact.py
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from fish.forms import ContactForm


# お問い合わせ
class ContactFormView(FormView):
    template_name = 'contact/contact_form.html'
    form_class = ContactForm
    success_url = reverse_lazy('fish:contact_result')

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)

contact_form = ContactFormView.as_view()


# 問い合わせ完了
class ContactResultView(TemplateView):
    template_name = 'contact/contact_result.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['success'] = "お問い合わせは正常に送信されました。"
        return context

contact_result = ContactResultView.as_view()

app/fish/views/create.py
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.views.generic import CreateView
from django.urls import reverse_lazy
from fish.models import Category, Place
from fish.forms import CategoryForm, PlaceForm


# カテゴリー追加
class CategoryCreateView(CreateView, LoginRequiredMixin):
    template_name = 'create/category_create.html'
    success_url = reverse_lazy('fish:article_create')
    form_class = CategoryForm
    model = Category

    def form_valid(self, form):
        form = form.save(commit=False)
        form.user = self.request.user
        form.save()
        return redirect('fish:article_create')

category_create = CategoryCreateView.as_view()


#　場所追加
class PlaceCreateView(CreateView, LoginRequiredMixin):
    template_name = 'create/place_create.html'
    success_url = reverse_lazy('fish:article_create')
    form_class = PlaceForm
    model = Place

    def form_valid(self, form):
        form = form.save(commit=False)
        form.user = self.request.user
        form.save()
        return redirect('fish:article_create')

place_create = PlaceCreateView.as_view()

app/fish/views/home.py
from django.views.generic import ListView
from fish.models import Article, Profile


# メイン画面
class IndexView(ListView):
    model = Article
    paginate_by = 6
    template_name = 'index.html'
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['profile_list'] = Profile.objects.filter(user_id=self.request.user.id)
        return context
    
    def get_queryset(self):
        queryset = Article.objects.order_by('-created_at')
        return queryset

index = IndexView.as_view()



#みんなの釣果
class EveryFishResultView(ListView):
    model = Article
    template_name = 'fish/every_fish_results.html'
    paginate_by = 24

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['profile_list'] = Profile.objects.filter(user_id=self.request.user.id)
        return context


    def get_queryset(self):
        queryset = Article.objects.order_by('-created_at')
        return queryset

every_result = EveryFishResultView.as_view()

app/fish/views/search.py
from django.contrib import messages
from django.views.generic import TemplateView, ListView
from fish.models import Article, Category, Place, Profile
from django.db.models import Q


# 検索
class SearchView(ListView):
    model = Article
    template_name = 'search/search.html'
    paginate_by = 24

    def get_queryset(self):
        queryset = Article.objects.order_by('-created_at')
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(Q(fish_category__title__icontains=keyword)|Q(place__title__icontains=keyword))
            messages.success(self.request, '「{}」の検索結果'.format(keyword))
        return queryset

search = SearchView.as_view()


# 魚種検索ページ
class CategorySearchView(TemplateView):
    template_name = 'search/category_search.html'

category_search = CategorySearchView.as_view()


# 魚種検索結果
class CategoryResultView(ListView):
    model = Article
    template_name = 'search/category_result.html'
    paginate_by = 24

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['profile_list'] = Profile.objects.filter(user_id=self.request.user.id)
        return context

    def get_queryset(self):
        queryset = Article.objects.order_by('-created_at')
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(Q(fish_category__title__icontains=keyword))
            messages.success(self.request, '「{}」の検索結果'.format(keyword))
        return queryset

category_result = CategoryResultView.as_view()


# 場所検索
class PlaceSearchView(TemplateView):
    template_name = 'search/place_search.html'

place_search = PlaceSearchView.as_view()


# 場所検索結果
class PlaceResultView(ListView):
    model = Article
    template_name = 'search/place_result.html'
    paginate_by = 24

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['profile_list'] = Profile.objects.filter(user_id=self.request.user.id)
        return context

    def get_queryset(self):
        queryset = Article.objects.order_by('-created_at')
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(Q(place__title__icontains=keyword))
            messages.success(self.request, '「{}」の検索結果'.format(keyword))
        return queryset

place_result = PlaceResultView.as_view()

app/fish/views/user.py
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.views.generic import UpdateView, DetailView
from django.urls import reverse
from fish.models import Article, Profile
from fish.forms import ProfileForm


# ユーザーページ
class UserPageDetailView(DetailView):
    template_name = 'profile/mypage.html'
    model = Profile

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['Article_list'] = Article.objects.filter(user=self.object.user).order_by('-created_at')[:15]
        return context

mypage_detail = UserPageDetailView.as_view()



# ユーザーページング
class UserPadingDetailView(DetailView):
    template_name = 'profile/mypading.html'
    model = Profile

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['Article_list'] = Article.objects.filter(user=self.object.user).order_by('-created_at')[:15]
        return context

mypage_pading = UserPadingDetailView.as_view()


# プロフィール編集
class UserPageUpdateView(UpdateView, LoginRequiredMixin):
    template_name = 'profile/profile_edit.html'
    form_class = ProfileForm
    model = Profile

    def get_success_url(self):
        return reverse('fish:mypage_detail', kwargs={'pk': self.object.pk})

profile_edit = UserPageUpdateView.as_view()

app/fish/templates/search/category_result.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block title %}
{{request.GET.keyword}}
{% endblock %}

{% block content %}

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<link rel="stylesheet" type="text/css" href="{% static 'css/search_result.css' %}">

<h1 class="keyword_position">{{request.GET.keyword}}の検索結果</h1>　　
<div class="NewPost-parent">
    {% for fish in object_list %}
    
    
    <a href="{% url 'fish:article_detail' fish.pk %}">
        <div class="NewPost-margin">
            <div class="new_list_border">
                <img src="{{ fish.fish_img.url }}" class="new_list_photo">
                <div class="new_list_margin">

                    
                    <div class="new_list_day">
                        {{ fish.created_at }}
                    </div>

                    <div class="new_list_category">
                        魚：{{ fish.fish_category }}
                        <div class="new_list_length">{{ fish.length }}cm</div>
                    </div>

                    <div class="new_list_place">
                        {{ fish.place }}
                    </div>
                </div>
            </div>
        </div>
    </a>
    {% endfor %}

    <div class="posi-padiing">

    <nav aria-label="Page navigation example">

        <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28">
            <!-- 前へ の部分 -->
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
    
            <!-- 数字の部分 -->
            {% for num in page_obj.paginator.page_range %}
                {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}
    
                    {% if page_obj.number == num %}
                        <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}
    
            <!-- 次へ の部分 -->
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    
    </nav>
    </div>
    
</div>
        <a href="{% url 'fish:index' %}">トップページに戻る</a>

        <footer class="index-footer">
            　　<ul class="footer-menu">
        
                 <a href="{% url 'fish:index' %}">
                    <li> 利用規約 ｜</li>
                </a>
        
                 <a href="{% url 'fish:index' %}">
                    <li>ホーム ｜</li>
                </a>
        
                <a href="{% url 'fish:contact_form' %}">
                    <li>お問い合わせ </li>
                 </a>
        
                </ul>
                
              </footer>
    {% endblock %}

app/fish/templates/search/category_search.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}

{% block title %}
魚種検索
{% endblock %}

{% block content %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

<img src="{% static 'img/umi.jpg' %}" class="top_pic">


<h2 class="place_margin">釣りたい魚の状態を調べよう！！</h2>

<div>

    <form method="get" action="{% url 'fish:category_result' %}" class="search-eria">
        <input type="text" size="25" placeholder="魚種検索" name="keyword">
        <input type="submit" value="&#xf002">
      </form>
</div>  



<h2 class="index_margin">人気のターゲット</h2>
 
<div class="flex_category">
    <tr>       
        <a href="/category_result/?keyword=%E3%83%96%E3%83%A9%E3%83%83%E3%82%AF%E3%83%90%E3%82%B9">
            <div class="border-radius_category">
            <div class="main-fl"></div>
                <td><img class="category_img" src="{% static 'img/IMG_2056.jpeg' %}"></td>
                <h1 class="category-p">ブラックバス</h1>
            </div>
        </a>

        <a href="/category_result/?keyword=%E3%83%88%E3%83%A9%E3%82%A6%E3%83%88">
            <div class="border-radius_category">
            <div class="main-fl"></div>
                <td><img class="category_img" src="{% static 'img/IMG_3067.jpeg' %}"></td>
                <h1 class="category-p">トラウト</h1>
        </div>
        </a>
        <a href="/category_result/?keyword=%E3%82%B7%E3%83%BC%E3%83%90%E3%82%B9">
            <div class="border-radius_category">
            <div class="main-fl"></div>
                <td><img class="category_img" src="{% static 'img/IMG_3071.jpeg' %}"></td>
                <h1 class="category-p">シーバス</h1>
        </div>
        </a>
    
        <a href="/category_result/?keyword=%E3%82%A2%E3%82%B8">
            <div class="border-radius_category">
                <td><img class="category_img" src="{% static 'img/IMG_0035.jpeg' %}"></td>
                <h1 class="category-p">アジ</h1>
            </div>
        </a>

    </tr>
    </div>

<h2 class="index_margin">人気のエリア</h2>

<div class="flex_category">
    <tr>       
        <a href="/place_result/?keyword=%E6%9D%B1%E4%BA%AC%E6%B9%BE">
            <div class="border-radius_category">
            <div class="main-fl"></div>
                <td><img class="category_img" src="{% static 'img/tokyo.jpg' %}"></td>
                <h1 class="category-p">東京湾</h1>
        </div>
        </a>

        <a href="/place_result/?keyword=%E7%90%B5%E7%90%B6%E6%B9%96">
            <div class="border-radius_category">
            <div class="main-fl"></div>
                <td><img class="category_img" src="{% static 'img/biwa.jpg' %}"></td>
                <h1 class="category-p">琵琶湖</h1>
        </div>
        </a>
        <a href="/place_result/?keyword=%E9%A7%BF%E6%B2%B3%E6%B9%BE">
            <div class="border-radius_category">
            <div class="main-fl"></div>
                <td><img class="category_img" src="{% static 'img/suruga.jpg' %}"></td>
                <h1 class="category-p">駿河湾</h1>
        </div>
        </a>
    
        <a href="/place_result/?keyword=%E7%80%AC%E6%88%B8%E5%86%85">
            <div class="border-radius_category">
                <td><img class="category_img" src="{% static 'img/setouti.jpg' %}"></td>
                <h1 class="category-p">瀬戸内</h1>
            </div>
        </a>
    </tr>
    </div>

    <footer class="index-footer">
        　　<ul class="footer-menu">

             <a href="{% url 'fish:index' %}">
                <li> 利用規約 ｜</li>
            </a>

             <a href="{% url 'fish:index' %}">
                <li>ホーム ｜</li>
            </a>

            <a href="{% url 'fish:contact_form' %}">
                <li>お問い合わせ </li>
             </a>

            </ul>
            
          </footer>
{% endblock %}

app/fish/templates/search/place_search.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}

{% block title %}
場所検索
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
<img src="{% static 'img/umi.jpg' %}" class="top_pic">

<h2 class="place_margin">みんながどこで釣っているか参考にしよう！！</h2>

<div>

    <form method="get" action="{% url 'fish:place_result' %}" class="search-eria">
        <input type="text" size="25" placeholder="場所検索" name="keyword">
        <input type="submit" value="&#xf002">
      </form>
</div>  

<h2 class="index_margin">人気のエリア</h2>

<div class="flex_category">
    <tr>       
        <a href="/place_result/?keyword=%E6%9D%B1%E4%BA%AC%E6%B9%BE">
            <div class="border-radius_category">
            <div class="main-fl"></div>
                <td><img class="category_img" src="{% static 'img/tokyo.jpg' %}"></td>
                <h1 class="category-p">東京湾</h1>
        </div>
        </a>

        <a href="/place_result/?keyword=%E7%90%B5%E7%90%B6%E6%B9%96">
            <div class="border-radius_category">
            <div class="main-fl"></div>
                <td><img class="category_img" src="{% static 'img/biwa.jpg' %}"></td>
                <h1 class="category-p">琵琶湖</h1>
        </div>
        </a>
        <a href="/place_result/?keyword=%E9%A7%BF%E6%B2%B3%E6%B9%BE">
            <div class="border-radius_category">
            <div class="main-fl"></div>
                <td><img class="category_img" src="{% static 'img/suruga.jpg' %}"></td>
                <h1 class="category-p">駿河湾</h1>
        </div>
        </a>
    
        <a href="/place_result/?keyword=%E7%80%AC%E6%88%B8%E5%86%85">
            <div class="border-radius_category">
                <td><img class="category_img" src="{% static 'img/setouti.jpg' %}"></td>
                <h1 class="category-p">瀬戸内</h1>
            </div>
        </a>

    </tr>
    </div>

    <h2 class="index_margin">人気のターゲット</h2>

<div class="flex_category">
    <tr>       
        <a href="/category_result/?keyword=%E3%83%96%E3%83%A9%E3%83%83%E3%82%AF%E3%83%90%E3%82%B9">
            <div class="border-radius_category">
            <div class="main-fl"></div>
                <td><img class="category_img" src="{% static 'img/IMG_2056.jpeg' %}"></td>
                <h1 class="category-p">ブラックバス</h1>
            </div>
        </a>

        <a href="/category_result/?keyword=%E3%83%88%E3%83%A9%E3%82%A6%E3%83%88">
            <div class="border-radius_category">
            <div class="main-fl"></div>
                <td><img class="category_img" src="{% static 'img/IMG_3067.jpeg' %}"></td>
                <h1 class="category-p">トラウト</h1>
        </div>
        </a>
        <a href="/category_result/?keyword=%E3%82%B7%E3%83%BC%E3%83%90%E3%82%B9">
            <div class="border-radius_category">
            <div class="main-fl"></div>
                <td><img class="category_img" src="{% static 'img/IMG_3071.jpeg' %}"></td>
                <h1 class="category-p">シーバス</h1>
        </div>
        </a>
    
        <a href="/category_result/?keyword=%E3%82%A2%E3%82%B8">
            <div class="border-radius_category">
                <td><img class="category_img" src="{% static 'img/IMG_0035.jpeg' %}"></td>
                <h1 class="category-p">アジ</h1>
            </div>
        </a>

    </tr>
    </div>


    <footer class="index-footer">
        　　<ul class="footer-menu">

             <a href="{% url 'fish:index' %}">
                <li> 利用規約 ｜</li>
            </a>

             <a href="{% url 'fish:index' %}">
                <li>ホーム ｜</li>
            </a>

            <a href="{% url 'fish:contact_form' %}">
                <li>お問い合わせ </li>
             </a>

            </ul>
            
          </footer>


{% endblock %}